apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: prom-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-demo
  template:
    metadata:
      labels:
        app: prom-demo
    spec:
      containers:
      - name: server
        image: server
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
        resources:
          requests:
            cpu: 250m
            memory: 50Mi
          limits:
            cpu: 250m
            memory: 50Mi
