kind: Service
apiVersion: v1
metadata:
  name: prom-demo
  labels:
    app: prom-demo
spec:
  selector:
    app: prom-demo
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30000
    targetPort: 3000
  type: NodePort
